## System chart for the controlling of argo-workflows
##
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argo-workflows"
  namespace: "argocd"
spec:
  destination:
    name: "in-cluster"
    namespace: "argo"
  source:
    path: "k8s-operations/charts/argo-workflows"
    repoURL: 'https://github.com/compsecmonkey/homelab'
    targetRevision: "HEAD"
    helm:
      version: v3
      valueFiles:
      - values.yaml
  project: "default"
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true